apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petunia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petunia.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: villadiana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: www
              containerPort: 8080
