apiVersion: v1
kind: Service
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  type: {{ (index .Values.ports 0).type }}
  selector:
    {{- include "petunia.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .name }}
    {{- end }}
