# The ingress front controller

tls:
  enabled: false

hosts:
  - host: sonar
    paths:
      - path: /
        service:
          name: sonar
          port: 9000
  - host: excalidraw
    paths:
      - path: /
        service:
          name: excalidraw
          port: 80
  - host: nakadi
    paths:
      - path: /
        service:
          name: nakadi
          port: 80
  - host: nakadi-ui
    paths:
      - path: /
        service:
          name: nakadi-ui
          port: 3000
  - host: sonar
    paths:
      - path: /
        service:
          name: sonarqube
          port: 9000
  - host: keycloak
    enabled: true
    paths:
      - path: /
        service:
          name: keycloak
          port: 8080
  - host: polonium
    enabled: true
    paths:
      - path: /
        service:
          name: polonium
          port: 8080
  - host: villadiana
    enabled: false
    paths:
      - path: /ws
        service:
          name: villadiana
          port: 8080
      - path: /api
        service:
          name: villadiana
          port: 8080
      - path: /oauth2
        service:
          name: villadiana
          port: 8080
      - path: /login
        service:
          name: villadiana
          port: 8080
      - path: /logout
        service:
          name: villadiana
          port: 8080
      - path: /me
        service:
          name: villadiana
          port: 8080
      - path: /
        service:
          name: alpicola
          port: 80