apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-root-password: {{ .Values.postgres.rootPassword | default "postgres" | quote }}
