replicaCount: 1

image:
  repository: excalidraw/excalidraw
  tag: "latest"
  pullPolicy: IfNotPresent

ports:
  - name: http
    type: ClusterIP
    containerPort: 80
    servicePort: 80

resources: {}
