replicaCount: 1

image:
  repository: roskenet/polonium
  tag: "3.3.0"
  pullPolicy: IfNotPresent

ports:
  - name: http
    type: ClusterIP
    containerPort: 8080
    servicePort: 8080

resources: {}
