apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    run: keycloak
    context: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 80
    targetPort: service 

