apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-data
  hostPath:
    path: /data/kafka-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kafka-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-secrets
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-secrets
  hostPath:
    path: /data/kafka-secrets
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-secrets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kafka-secrets
