apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-data
  hostPath:
    path: /data/zookeeper-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zookeeper-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-datalog
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-datalog
  hostPath:
    path: /data/zookeeper-datalog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-datalog-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zookeeper-datalog
