apiVersion: v1
kind: Service
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: service
      protocol: TCP
      name: http
  selector:
    {{- include "petunia.selectorLabels" . | nindent 4 }}

