apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petunia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petunia.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        {{- range $i, $vol := .Values.persistence.volumes }}
        - name: {{ $vol.name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" (include "petunia.fullname" $) $vol.name | trunc 63 | trimSuffix "-" }}
        {{- end }}
      containers:
        - name: zookeeper
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZOO_ADMINSERVER_ENABLED
              value: "{{ .Values.zookeeper.disableAdmin }}"
          volumeMounts:
          {{- range $i, $vol := .Values.persistence.volumes }}
            - mountPath: {{ $vol.mountPath }}
              name: {{ $vol.name }}
          {{- end }}
