apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    app: postgres
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-data
  hostPath:
    path: /mnt/postgres-data
