apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petunia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petunia.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nakadi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
