apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petunia.fullname" . }}
  labels:
    {{- include "petunia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petunia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petunia.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: villadiana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: KEYCLOAK_ISSUER_URI
            - name: KEYCLOAK_TOKEN_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: KEYCLOAK_TOKEN_URI
            - name: NAKADI_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: NAKADI_URI
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: ALLOWED_ORIGINS
            - name: POST_LOGOUT_REDIRECT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: POST_LOGOUT_REDIRECT
            - name: POST_LOGIN_REDIRECT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: POST_LOGIN_REDIRECT
            - name: AXILLARIS_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "petunia.fullname" . }}-config
                  key: AXILLARIS_URI
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: {{ .Values.keycloakSecretKey }}
          ports:
            - name: www
              containerPort: 8080
