spring:
  session:
    store-type: redis
    redis:
      namespace: petunia:session
    timeout: 30m
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak/realms/petunia}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak/realms/petunia/protocol/openid-connect/token}
        registration:
          keycloak:
            client-id: villadiana
            client-secret: ${KEYCLOAK_SECRET:6w8HibfpYVEQIgMTKAFXFPMC8NgaOHBU}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            provider: keycloak
          axillaris-client:
            client-id: villadiana
            client-secret: ${KEYCLOAK_SECRET:6w8HibfpYVEQIgMTKAFXFPMC8NgaOHBU}
            authorization-grant-type: client_credentials
            scope: petunias.read,petunias.write
            provider: keycloak
management:
  otlp:
    metrics:
      export:
        url: "http://otel-collector:4318/v1/metrics"
        step: 10s
        enabled: false
  metrics:
    tags:
      service.name: villadiana

  endpoints:
    web:
      exposure:
        include: health
