spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/petunia
            token-uri: http://keycloak/realms/petunia/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: villadiana
            client-secret: 6w8HibfpYVEQIgMTKAFXFPMC8NgaOHBU
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            provider: keycloak
          axillaris-client:
            client-id: villadiana
            client-secret: 6w8HibfpYVEQIgMTKAFXFPMC8NgaOHBU
            authorization-grant-type: client_credentials
            scope: petunias.read,petunias.write
            provider: keycloak

management:
  otlp:
    metrics:
      export:
        enabled: off

NAKADI_URI: http://nakadi
ALLOWED_ORIGINS: http://localhost:3000
POST_LOGOUT_REDIRECT: https://localhost:3000
POST_LOGIN_REDIRECT: https://localhost:3000/petunias